# 100 Numpy Exercises
Taken from [here](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md)

In [1]:
import numpy as np

Print the numpy versions and configuration

In [2]:
%who

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [5]:
print(np.__version__)
# np.show_config()

1.16.5


Create a null vector of size 10

In [3]:
z = np.zeros(10, dtype=int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Get the memory size of an array

In [4]:
z = np.zeros(10, dtype='int8')
print(f'The vector {z} of type {z.dtype} takes up {z.size} x {z.itemsize} = {z.nbytes} bytes')
z = np.zeros(10, dtype='int16')
print(f'The vector {z} of type {z.dtype} takes up {z.size} x {z.itemsize} = {z.nbytes} bytes')
z = np.zeros(10, dtype='int32')
print(f'The vector {z} of type {z.dtype} takes up {z.size} x {z.itemsize} = {z.nbytes} bytes')

The vector [0 0 0 0 0 0 0 0 0 0] of dtype int8 takes up 10 x 1 = 10 bytes
The vector [0 0 0 0 0 0 0 0 0 0] of dtype int16 takes up 10 x 2 = 20 bytes
The vector [0 0 0 0 0 0 0 0 0 0] of dtype int32 takes up 10 x 4 = 40 bytes


Make the fifth value 1

In [5]:
z[4] = 1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Create a vector from 10 to 49

In [1]:
z = np.arange(10, 50)
z

NameError: name 'np' is not defined

Reverse a vector

In [7]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Create a 3 x 3 matrix from 0 to 8

In [8]:
z = np.arange(9).reshape((3,3))
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements

In [17]:
z = np.random.randint(0, 2, size=9)
print('Take an array', z)
# Index for 1D array
print('The non-zero elements are at', np.flatnonzero(z)) 
# Index for 2D array
print('The non-zero elements are at', np.nonzero(z))
# nonzero is also a method
print('The non-zero elements are at', z.nonzero())
# Can also use np.where
print('The non-zero elements are at', np.where(z!=0))
# Can use np.nonzero to find any element
print('The zero elements are at', np.nonzero(z==0))
print('The zero elements are at', np.where(z==0))

Take an array [1 0 0 0 0 1 1 0 0]
The non-zero elements are at [0 5 6]
The non-zero elements are at (array([0, 5, 6], dtype=int64),)
The non-zero elements are at (array([0, 5, 6], dtype=int64),)
The non-zero elements are at (array([0, 5, 6], dtype=int64),)
The zero elements are at (array([1, 2, 3, 4, 7, 8], dtype=int64),)
The zero elements are at (array([1, 2, 3, 4, 7, 8], dtype=int64),)


Create a 3x3 identity matrix

In [10]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a 3x3x3 array of random values

In [11]:
np.round(np.random.random((3,3,3)),2)

array([[[0.92, 0.02, 0.07],
        [0.94, 0.97, 0.52],
        [0.24, 0.84, 0.18]],

       [[0.01, 0.8 , 0.52],
        [0.39, 0.8 , 0.28],
        [0.43, 0.62, 0.17]],

       [[0.09, 0.21, 0.57],
        [0.82, 0.71, 0.25],
        [0.18, 0.47, 0.75]]])

Create a 10x10 array of random values and find the min and max

In [12]:
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
zmin, zmax

(0.002501954172831944, 0.9978928063275445)

Create a random vector of size 30 and find the mean

In [13]:
z = np.random.random(30)
z.mean()

0.46577868719311016

Create a 2D array with 1 on the boarder and 0 in the middle

In [14]:
z = np.ones((5,5), dtype=int)
z[1:-1,1:-1] = 0
z

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Add a border of zeros around an existing array

In [15]:
z = np.array([[1, 2], [3, 4]])
np.pad(z, 1, mode='constant')

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [16]:
# You can also pad with different modes such as constant, edge, linear_ramp, min/maximum, mean, median, reflect, symmetric, wrap
print("mode='edge'")
print(np.pad(z, 2, 'edge'))
print("mode='minimum'")
print(np.pad(z, 2, 'minimum'))
print("mode='symmetric'")
print(np.pad(z, 2, 'symmetric'))
print("mode='wrap'")
print(np.pad(z, 2, 'wrap'))


mode='edge'
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]
mode='minimum'
[[1 1 1 2 1 1]
 [1 1 1 2 1 1]
 [1 1 1 2 1 1]
 [3 3 3 4 3 3]
 [1 1 1 2 1 1]
 [1 1 1 2 1 1]]
mode='symmetric'
[[4 3 3 4 4 3]
 [2 1 1 2 2 1]
 [2 1 1 2 2 1]
 [4 3 3 4 4 3]
 [4 3 3 4 4 3]
 [2 1 1 2 2 1]]
mode='wrap'
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


What is the result of expressions using `np.nan`?

In [25]:
# Mathematical operations using nan, equal nan
print('3 * np.nan =', 3 * np.nan)
print('np.nan + 3 =', 3 + np.nan)
print('min(np.nan, 3) =', min(np.nan,3))

# Booleans become false
print('np.inf > np.nan =', np.inf > np.nan)
print('np.nan == np.nan =', np.nan == np.nan)

# But you can check if nan is in a collection object
np.nan in [1, 2, 3, np.nan]

3 * np.nan = nan
np.nan + 3 = nan
min(np.nan, 3) = nan
np.inf > np.nan = False
np.nan == np.nan = False


True

Create a 5x5 matrix with 1, 2, 3, 4 just below the diagonal

In [26]:
np.diag(range(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Create an 8x8 checkerboard pattern

In [54]:
print('Method 1 - Set Alternate Elements')
z = np.zeros((8,8), dtype=int)
z[::2,1::2] = 1
z[1::2,::2] = 1
print(z)

print('Method 2 - Tile Identity Matrix')
z = np.tile(np.eye(2, dtype=int), (4,4))
print(z)

print('Method 3 - Pad (reflect mode) Identity Matrix')
np.pad(np.eye(2, dtype=int), 3, mode='reflect')
print(z)

Method 1 - Set Alternate Elements
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Method 2 - Tile Identity Matrix
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
Method 3 - Pad (reflect mode) Identity Matrix
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Normalize a 5x5 Matrix

In [64]:
z = np.random.random((5,5))
print('z is', z)

# Normalize
z = (z - z.mean()) / z.std()
print('Z is', z)

z is [[0.06609379 0.39518211 0.63287643 0.15711136 0.98995194]
 [0.36748568 0.52295616 0.11786199 0.09628768 0.07920712]
 [0.79114262 0.22097182 0.51037233 0.43329857 0.15981199]
 [0.69727677 0.67124343 0.10001057 0.86560445 0.02867618]
 [0.75956445 0.09116535 0.63379101 0.52762279 0.99131103]]
Z is [[-1.21030931 -0.13435371  0.64278883 -0.91272698  1.81024864]
 [-0.22490729  0.28340407 -1.04105296 -1.11159027 -1.16743522]
 [ 1.16024076 -0.70393495  0.24226119 -0.0097318  -0.90389727]
 [ 0.85334599  0.76822989 -1.09941824  1.40369402 -1.33264632]
 [ 1.05699582 -1.12833774  0.64577904  0.29866161  1.81469219]]


Create a custom dtype to describe a color as 4 unsigned bytes

In [71]:
color = np.dtype([('R', np.ubyte),
                  ('G', np.ubyte),
                  ('B', np.ubyte),
                  ('A', np.ubyte)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [97]:
z = np.array([(255, 0, 0, 0)], dtype=color)
z

array([(255, 0, 0, 0)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

Multiply a 3x5 matrix with a 5x2 matrix

In [257]:
A = np.random.randint(10, size=(3,5))
B = np.random.randint(10, size=(5,2))
print('A x B =', np.dot(A, B))
print('A x B =', A @ B)

A x B = [[138 102]
 [118 149]
 [124 148]]
A x B = [[138 102]
 [118 149]
 [124 148]]


ValueError: operands could not be broadcast together with shapes (3,5) (5,2) 

Negate all elements between 3 and 8

In [118]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

Compare the output

In [123]:
sum(range(5), -1)
# 9
np.sum(range(5), -1)
# 10

10

Which are legal for an integer vector?

In [145]:
z = np.arange(6)
print('z ** z =', z ** z)
# Divide each element by 2^2
print('z << 2 =', z << 2)
print('z <- z =', z < -z)
print('1j * z =', 1j * z)
print('z / 1 / 1 =', z / 1 / 1)

z ** z = [   1    1    4   27  256 3125]
z << 2 = [ 0  4  8 12 16 20]
z <- z = [False False False False False False]
1j * z = [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
z / 1 / 1 = [0. 1. 2. 3. 4. 5.]


What are the results of the following expressions?

In [156]:
print(np.array(0) / np.array(0))
# nan ...and a warning
print(np.array(0) // np.array(0))
# 0 ...and another warning
print(np.array(np.nan).astype(int))
# -2147483648 ... = 2 ^ 31


nan
0
-2147483648


C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


How to round away from zero

In [163]:
z = np.random.uniform(-10, 10, 10)
print('z =', z)
z = np.copysign(np.ceil(np.abs(z)), z)
print('z rounded away from 0 =', z)

z = [ 3.28799693 -4.94836598  7.88208664  2.25879557  7.59125414 -2.94327853
  0.24919431  7.35534802 -1.77171041 -7.66066915]
z rounded away from 0 = [ 4. -5.  8.  3.  8. -3.  1.  8. -2. -8.]


In [168]:
# Suicide mode on
# defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
# _ = np.seterr(**defaults)

C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [169]:
with np.errstate(divide='ignore'):
    z = np.ones(1) / 0

In [177]:
print('np.sqrt(-1) =', np.sqrt(-1))
# np.nan
print('np.emath.sqrt(-1) =', np.emath.sqrt(-1))
# 1j
print('np.sqrt(-1) == np.emath.sqrt(-1)', np.sqrt(-1) == np.emath.sqrt(-1))

np.sqrt(-1) = nan
np.emath.sqrt(-1) = 1j
np.sqrt(-1) == np.emath.sqrt(-1) False


C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


Get the datetime of today, yesterday and tomorrow

In [231]:
print('Today is', np.datetime64('today'))
print('Yesterday is', np.datetime64('today') - np.timedelta64(1))
print('Tomorrow is', np.datetime64('today') + np.timedelta64(1))

Today is 2019-12-27
Yesterday is 2019-12-26
Tomorrow is 2019-12-28


In [255]:
print('It is', np.datetime64('2020-01-25') - np.datetime64('today'), 'days until my birthday')

It is 29 days days until my birthday


Get all days in January 2020

In [222]:
today = np.datetime64('2020-01')
month = np.timedelta64(1, 'M')
np.arange(today, today + month, dtype='datetime64[D]')
# np.arange('2020-01-01', '2020-02-01', dtype='datetime64')

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
       '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
       '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31'], dtype='datetime64[D]')

Compute ((A+B)*(-A/2)) in place (without copy)?

In [268]:
A = 1 * np.ones(3)
B = 2 * np.ones(3)

print((A+B) * (-A/2))

# In place
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


Extract the integer part of an array

In [281]:
z = np.round(np.random.uniform(-10,10,10), 2)
print(z)
# Round down
print(z - z%1)
# Round down
print(z // 1)
# Round down
print(np.floor(z))
# Round down
print(np.ceil(z)-1)
# Remove the fractional part -> move closer to zero
print(np.trunc(z))
# Remove the fractional part -> move closer to zero
print(z.astype(int))

[-7.33 -7.7   3.76 -0.8   0.92  6.03 -0.56 -9.43 -3.88 -5.75]
[ -8.  -8.   3.  -1.   0.   6.  -1. -10.  -4.  -6.]
[ -8.  -8.   3.  -1.   0.   6.  -1. -10.  -4.  -6.]
[ -8.  -8.   3.  -1.   0.   6.  -1. -10.  -4.  -6.]
[ -8.  -8.   3.  -1.   0.   6.  -1. -10.  -4.  -6.]
[-7. -7.  3. -0.  0.  6. -0. -9. -3. -5.]
[-7 -7  3  0  0  6  0 -9 -3 -5]


Create a 5x5 matrix with row values ranging from 0 to 4

In [292]:
z = np.tile(np.arange(5), (5,1))
print(z)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
print('hello world')


In [6]:
a = 'test'
print(a)

test


In [ ]:
test