# 100 Numpy Exercises
Taken from [here](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md)

In [1]:
import numpy as np

Print the numpy versions and configuration

In [5]:
print(np.__version__)
# np.show_config()

1.16.5


Create a null vector of size 10

In [3]:
z = np.zeros(10, dtype=int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Get the memory size of an array

In [4]:
z = np.zeros(10, dtype='int8')
print(f'The vector {z} of type {z.dtype} takes up {z.size} x {z.itemsize} = {z.nbytes} bytes')
z = np.zeros(10, dtype='int16')
print(f'The vector {z} of type {z.dtype} takes up {z.size} x {z.itemsize} = {z.nbytes} bytes')
z = np.zeros(10, dtype='int32')
print(f'The vector {z} of type {z.dtype} takes up {z.size} x {z.itemsize} = {z.nbytes} bytes')

The vector [0 0 0 0 0 0 0 0 0 0] of type int8 takes up 10 x 1 = 10 bytes
The vector [0 0 0 0 0 0 0 0 0 0] of type int16 takes up 10 x 2 = 20 bytes
The vector [0 0 0 0 0 0 0 0 0 0] of type int32 takes up 10 x 4 = 40 bytes


Make the fifth value 1

In [5]:
z[4] = 1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Create a vector from 10 to 49

In [6]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Reverse a vector

In [7]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Create a 3 x 3 matrix from 0 to 8

In [8]:
z = np.arange(9).reshape((3,3))
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements

In [9]:
z = np.random.randint(0, 2, size=9)
print('Take an array', z)
# Index for 1D array
print('The non-zero elements are at', np.flatnonzero(z)) 
# Index for 2D array
print('The non-zero elements are at', np.nonzero(z))
# nonzero is also a method
print('The non-zero elements are at', z.nonzero())
# Can also use np.where
print('The non-zero elements are at', np.where(z!=0))
# Can use np.nonzero to find any element
print('The zero elements are at', np.nonzero(z==0))
print('The zero elements are at', np.where(z==0))

Take an array [0 1 1 0 1 0 1 1 0]
The non-zero elements are at [1 2 4 6 7]
The non-zero elements are at (array([1, 2, 4, 6, 7], dtype=int64),)
The non-zero elements are at (array([1, 2, 4, 6, 7], dtype=int64),)
The non-zero elements are at (array([1, 2, 4, 6, 7], dtype=int64),)
The zero elements are at (array([0, 3, 5, 8], dtype=int64),)
The zero elements are at (array([0, 3, 5, 8], dtype=int64),)


Create a 3x3 identity matrix

In [10]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Create a 3x3x3 array of random values

In [11]:
np.round(np.random.random((3,3,3)),2)

array([[[0.28, 0.89, 0.35],
        [0.94, 0.59, 0.33],
        [0.59, 0.69, 0.61]],

       [[0.55, 0.19, 0.16],
        [0.29, 0.43, 0.4 ],
        [0.8 , 0.32, 0.06]],

       [[0.68, 0.66, 0.24],
        [0.84, 0.47, 0.66],
        [0.62, 0.05, 0.98]]])

Create a 10x10 array of random values and find the min and max

In [12]:
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
zmin, zmax

(0.0039984561808886765, 0.9719619958702276)

Create a random vector of size 30 and find the mean

In [13]:
z = np.random.random(30)
z.mean()

0.4978470075515477

Create a 2D array with 1 on the boarder and 0 in the middle

In [14]:
z = np.ones((5,5), dtype=int)
z[1:-1,1:-1] = 0
z

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Add a border of zeros around an existing array

In [15]:
z = np.array([[1, 2], [3, 4]])
np.pad(z, 1, mode='constant')

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [16]:
# You can also pad with different modes such as constant, edge, linear_ramp, min/maximum, mean, median, reflect, symmetric, wrap
print("mode='edge'")
print(np.pad(z, 2, 'edge'))
print("mode='minimum'")
print(np.pad(z, 2, 'minimum'))
print("mode='symmetric'")
print(np.pad(z, 2, 'symmetric'))
print("mode='wrap'")
print(np.pad(z, 2, 'wrap'))


mode='edge'
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]
mode='minimum'
[[1 1 1 2 1 1]
 [1 1 1 2 1 1]
 [1 1 1 2 1 1]
 [3 3 3 4 3 3]
 [1 1 1 2 1 1]
 [1 1 1 2 1 1]]
mode='symmetric'
[[4 3 3 4 4 3]
 [2 1 1 2 2 1]
 [2 1 1 2 2 1]
 [4 3 3 4 4 3]
 [4 3 3 4 4 3]
 [2 1 1 2 2 1]]
mode='wrap'
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


What is the result of expressions using `np.nan`?

In [29]:
# Mathematical operations using nan evaluate to nan
print('\nMathematical operations using nan => nan')
print('3 * np.nan =', 3 * np.nan)
print('np.nan + 3 =', 3 + np.nan)
print('min(np.nan, 3) =', min(np.nan,3))

# Booleans become false
print('\nBooleans using nan evaluate to False')
print('np.inf > np.nan =', np.inf > np.nan)
print('np.nan == np.nan =', np.nan == np.nan)

# But you can check if nan is in a collection object
print('\nCheck nan in object')
print('np.nan in [1, 2, 3, np.nan] =', np.nan in [1, 2, 3, np.nan])


Mathematical operations using nan => nan
3 * np.nan = nan
np.nan + 3 = nan
min(np.nan, 3) = nan

Booleans using nan evaluate to False
np.inf > np.nan = False
np.nan == np.nan = False

Check nan in object
np.nan in [1, 2, 3, np.nan] = True


Create a 5x5 matrix with 1, 2, 3, 4 just below the diagonal

In [30]:
np.diag(range(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Create an 8x8 checkerboard pattern

In [40]:
print('Method 1 - Set Alternate Elements')
z = np.zeros((8,8), dtype=int)
z[::2,1::2] = 1
z[1::2,::2] = 1
print(z)

print('\nMethod 2 - Tile Identity Matrix')
z = np.tile(np.eye(2, dtype=int), (4,4))
print(z)

print('\nMethod 3 - Pad (reflect mode) Identity Matrix')
z = np.pad(np.eye(2, dtype=int), 3, mode='reflect')
print(z)

Method 1 - Set Alternate Elements
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

Method 2 - Tile Identity Matrix
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

Method 3 - Pad (reflect mode) Identity Matrix
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Normalize a 5x5 Matrix

In [64]:
z = np.random.random((5,5))
print('z is', z)

# Normalize
z = (z - z.mean()) / z.std()
print('Z is', z)

z is [[0.06609379 0.39518211 0.63287643 0.15711136 0.98995194]
 [0.36748568 0.52295616 0.11786199 0.09628768 0.07920712]
 [0.79114262 0.22097182 0.51037233 0.43329857 0.15981199]
 [0.69727677 0.67124343 0.10001057 0.86560445 0.02867618]
 [0.75956445 0.09116535 0.63379101 0.52762279 0.99131103]]
Z is [[-1.21030931 -0.13435371  0.64278883 -0.91272698  1.81024864]
 [-0.22490729  0.28340407 -1.04105296 -1.11159027 -1.16743522]
 [ 1.16024076 -0.70393495  0.24226119 -0.0097318  -0.90389727]
 [ 0.85334599  0.76822989 -1.09941824  1.40369402 -1.33264632]
 [ 1.05699582 -1.12833774  0.64577904  0.29866161  1.81469219]]


Create a custom dtype to describe a color as 4 unsigned bytes

In [42]:
color = np.dtype([('R', np.ubyte),
                  ('G', np.ubyte),
                  ('B', np.ubyte),
                  ('A', np.ubyte)])
color

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

In [43]:
# Use the color dtype
z = np.array([(255, 0, 0, 0)], dtype=color)
z

array([(255, 0, 0, 0)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

Multiply a 3x5 matrix with a 5x2 matrix

In [44]:
A = np.random.randint(10, size=(3,5))
B = np.random.randint(10, size=(5,2))
print('A x B =', np.dot(A, B))

# Use @ sign shortcut for matrix multiplication
print('A x B =', A @ B)

A x B = [[128  79]
 [204 155]
 [ 72  60]]
A x B = [[128  79]
 [204 155]
 [ 72  60]]


Negate all elements between 3 and 8

In [46]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

Compare the output

In [106]:
print(sum(range(5), -1))
# 9
print(np.sum(range(5), -1))
# 10

9
10


In [117]:
# The second (start) parameter in default sum adds a constant number.
print(sum([], 99))

# The second parameter (axis) in np.sum specifies the direction
z = np.array([[1,2],[3,4]])
print(z)
print('Sum along axis = 0 (v)', z.sum(0))
print('Sum along axis = 1 (h)', z.sum(1))
print('Sum along axis = -1 (h)', z.sum(-1))

99
[[1 2]
 [3 4]]
Sum along axis = 0 (v) [4 6]
Sum along axis = 1 (h) [3 7]
Sum along axis = -1 (h) [3 7]


Which are legal for an integer vector?

In [122]:
z = np.arange(6)
print('z =', z)
print('z ** z =', z ** z)
# Divide each element by 2^2
print('z << 2 =', z << 2)
print('z <- z =', z < -z)
print('1j * z =', 1j * z)
print('z / 1 / 1 =', z / 1 / 1)

z = [0 1 2 3 4 5]
z ** z = [   1    1    4   27  256 3125]
z << 2 = [ 0  4  8 12 16 20]
z <- z = [False False False False False False]
1j * z = [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
z / 1 / 1 = [0. 1. 2. 3. 4. 5.]


In [161]:
help('<<')

Operator precedence
*******************

The following table summarizes the operator precedence in Python, from
lowest precedence (least binding) to highest precedence (most
binding).  Operators in the same box have the same precedence.  Unless
the syntax is explicitly given, operators are binary.  Operators in
the same box group left to right (except for exponentiation, which
groups from right to left).

Note that comparisons, membership tests, and identity tests, all have
the same precedence and have a left-to-right chaining feature as
described in the Comparisons section.

+-------------------------------------------------+---------------------------------------+
| Operator                                        | Description                           |
|=================================================|=======================================|
| "lambda"                                        | Lambda expression                     |
+------------------------------------------------

What are the results of the following expressions?

In [162]:
print(np.array(0) / np.array(0))
# nan ...and a warning
print(np.array(0) // np.array(0))
# 0 ...and another warning
print(np.array(np.nan).astype(int))
# -2147483648 ... = 2 ^ 31


nan
0
-2147483648
C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


How to round away from zero

In [163]:
z = np.random.uniform(-10, 10, 10)
print('z =', z)
z = np.copysign(np.ceil(np.abs(z)), z)
print('z rounded away from 0 =', z)

z = [-2.50602502  1.07879637 -6.83324231  1.25776002 -9.36581791  1.49789111
  6.59034853 -8.03355807 -7.51039319  0.0730206 ]
z rounded away from 0 = [ -3.   2.  -7.   2. -10.   2.   7.  -9.  -8.   1.]


In [165]:
# Suicide mode on
# defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
# _ = np.seterr(**defaults)

C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [167]:
with np.errstate(divide='ignore'):
    z = np.ones(1) / 0

In [169]:
print('np.sqrt(-1) =', np.sqrt(-1))
# np.nan
print('np.emath.sqrt(-1) =', np.emath.sqrt(-1))
# 1j
print('np.sqrt(-1) == np.emath.sqrt(-1)', np.sqrt(-1) == np.emath.sqrt(-1))

np.sqrt(-1) = nan
np.emath.sqrt(-1) = 1j
np.sqrt(-1) == np.emath.sqrt(-1) False
C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
C:\Users\Philip\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


Get the datetime of today, yesterday and tomorrow

In [170]:
print('Today is', np.datetime64('today'))
print('Yesterday is', np.datetime64('today') - np.timedelta64(1))
print('Tomorrow is', np.datetime64('today') + np.timedelta64(1))

Today is 2019-12-29
Yesterday is 2019-12-28
Tomorrow is 2019-12-30


In [171]:
print('It is', np.datetime64('2020-01-25') - np.datetime64('today'), 'days until my birthday')

It is 27 days days until my birthday


Get all days in January 2020

In [172]:
today = np.datetime64('2020-01')
month = np.timedelta64(1, 'M')
np.arange(today, today + month, dtype='datetime64[D]')
# np.arange('2020-01-01', '2020-02-01', dtype='datetime64')

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
       '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
       '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31'], dtype='datetime64[D]')

Compute ((A+B)*(-A/2)) in place (without copy)?

In [173]:
A = 1 * np.ones(3)
B = 2 * np.ones(3)

print((A+B) * (-A/2))

# In place
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
np.multiply(A, B, out=A)
print(A)

[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


Extract the integer part of an array

In [175]:
z = np.round(np.random.uniform(-10,10,10), 2)
print(z)
# Round down
print(z - z%1)
# Round down
print(z // 1)
# Round down
print(np.floor(z))
# Round down
print(np.ceil(z)-1)
# Remove the fractional part -> move closer to zero
print(np.trunc(z))
# Remove the fractional part -> move closer to zero
print(z.astype(int))

[ 8.02 -7.08  1.9  -5.05  6.15  7.43 -2.07  8.29  5.68  1.59]
[ 8. -8.  1. -6.  6.  7. -3.  8.  5.  1.]
[ 8. -8.  1. -6.  6.  7. -3.  8.  5.  1.]
[ 8. -8.  1. -6.  6.  7. -3.  8.  5.  1.]
[ 8. -8.  1. -6.  6.  7. -3.  8.  5.  1.]
[ 8. -7.  1. -5.  6.  7. -2.  8.  5.  1.]
[ 8 -7  1 -5  6  7 -2  8  5  1]


Create a 5x5 matrix with row values ranging from 0 to 4

In [176]:
z = np.tile(np.arange(5), (5,1))
print(z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
