# Numpy
**Exploration of the Numpy Package**

**Todo**
* Clean up the Raw cell below

In [103]:
import numpy as np

Create some numpy arrays

In [99]:
a = np.array([[0,1,2],[3,4,5]])
print('State with np.array\n', a)

b = np.arange(6).reshape(2,3, order='C')  # F to order by rows 
print('\nCreate arange and reshape\n', b)

c = np.vstack((range(3), range(3,6)))
print('\nVertically stack with np.vstack [0,1,2] and [3,4,5]\n', c)

State with np.array
 [[0 1 2]
 [3 4 5]]

Create arange and reshape
 [[0 1 2]
 [3 4 5]]

Vertically stack with np.vstack [0,1,2] and [3,4,5]
 [[0 1 2]
 [3 4 5]]


Create some more

In [100]:
full = np.full((2,3), 99)
print('\nFull with np.full\n', full)

ones = np.ones((2,3), dtype=int)
print('\nOnes with np.ones\n', ones)

zeros = np.zeros((2,3), dtype=int)
print('\nZeros with np.zeros\n', zeros)

eye = np.eye(2,3, k=1, dtype=int)
print('\nIdentity matrix with np.eye\n', eye)

diag = np.diag([1,2], k=1)[:-1]
print('\nDiagonal sliced (for 2x3 matrix) with np.diag\n', diag)

tri = np.tri(2, 3, k=1, dtype=int)
print('\nOnes at and below the diagonal\n', tri)

empty = np.empty((2,3))
print('\nEmpty with np.empty\n', empty)


Full with np.full
 [[99 99 99]
 [99 99 99]]

Ones with np.ones
 [[1 1 1]
 [1 1 1]]

Zeros with np.zeros
 [[0 0 0]
 [0 0 0]]

Identity matrix with np.eye
 [[0 1 0]
 [0 0 1]]

Diagonal sliced (for 2x3 matrix) with np.diag
 [[0 1 0]
 [0 0 2]]

Ones at and below the diagonal
 [[1 1 0]
 [1 1 1]]

Empty with np.empty
 [[3.14 3.14 3.14]
 [3.14 3.14 3.14]]
